name: prek-action
description: Run pre-commit hooks using prek
inputs:
  extra_args:
    description: options to pass to prek run
    required: false
    default: '--all-files'
runs:
  using: composite
  steps:
  - name: Install uv
    uses: astral-sh/setup-uv@v6
  - run: uv tool install prek
    shell: bash
  - uses: actions/cache@v4
    with:
      path: ~/.cache/prek
      key: prek|${{ hashFiles('.pre-commit-config.yaml') }}
  - run: prek run --show-diff-on-failure --color=always ${{ inputs.extra_args }}
    shell: bash
branding:
  icon: 'git-commit'
  color: 'orange'
